### Example of the new tetrad


In [1]:
## conda install ipyrad -c ipyrad
## conda install toytree -c eaton-lab

In [2]:
import ipyrad as ip
import ipyrad.analysis as ipa
import toytree 
import h5py
import ipyparallel as ipp

In [3]:
## up-to-date versions 
print 'ip', ipa.__version__
print 'toytree', toytree.__version__

ip 0.7.13
toytree 0.1.4


In [5]:
## load finished ipyrad assembly
data = ip.load_json("/home/deren/local/src/ipyrad/tests/cli/cli.json")

loading Assembly: cli
from saved path: ~/local/src/ipyrad/tests/cli/cli.json


In [6]:
## init a tetrad analysis object
tet = ipa.tetrad(
    name=data.name,
    data=data.outfiles.snpsphy,
    mapfile=data.outfiles.snpsmap,
    nboots=10,
    save_invariants=True   ## <- new option to save the arrays
    )

loading seq array [12 taxa x 4325 bp]
max unlinked SNPs per quartet (nloci): 984


In [7]:
## show params
tet.params

method            all                 
nboots            10                  
nquartets         495                 
resolve_ambigs    True                
save_invariants   True                

In [8]:
## run inference
tet.run(force=True)

inferring 495 quartet tree sets
host compute node: [40 cores] on sacra
[####################] 100% generating q-sets | 0:00:00 |  
[####################] 100% initial tree      | 0:00:00 |  
[####################] 100% bootstrap trees   | 0:00:03 |  
[####################] 100% calculating stats | 0:00:00 |  


In [7]:
## show tree results
tet.trees

boots   ~/scratch/quartet_proj/analysis-tetrad/cli.boots
cons    ~/scratch/quartet_proj/analysis-tetrad/cli.cons
nhx     ~/scratch/quartet_proj/analysis-tetrad/cli.nhx
tree    ~/scratch/quartet_proj/analysis-tetrad/cli.tree

In [9]:
## explore database
with h5py.File(tet.database.output, 'r') as db:
    print 'keys in the database:', db.keys()
    print 'keys in the invariants db:', db['invariants'].keys()[:5]
    print 'example invariant array:', db['invariants']['boot1']
    print 'example quartets array:', db['quartets']    

keys in the database: [u'invariants', u'quartets']
keys in the invariants db: [u'boot0', u'boot1', u'boot10', u'boot2', u'boot3']
example invariant array: <HDF5 dataset "boot1": shape (495, 16, 16), type "<u2">
example quartets array: <HDF5 dataset "quartets": shape (495, 4), type "<u2">


In [9]:
## a 16x16 matrix for one quartet
with h5py.File(tet.database.output) as db:
    idx = 100
    qrt = db['quartets'][idx]
    arr = db['invariants/boot0']
    print 'inferred quartet:', qrt
    print 'matrix for ordered set:\n', arr[idx, :, :]

inferred quartet: [0 3 7 9]
matrix for ordered set:
[[ 0 21 24 27  7  4  0  0 26  0  3  0 17  0  0  0]
 [12  0  0  0  0 19  0  0  0  0  0  0  0  0  0  0]
 [16  0  0  0  0  0  0  0  0  0 10  0  0  0  0  0]
 [13  0  0  1  1  0  0  0  0  0  0  0  0  0  0 17]
 [16  0  0  0  0 10  0  0  0  0  0  0  0  0  0  0]
 [ 5 23  0  0 13  0 20 20  0 13  4  0  0 17  0  2]
 [ 0  0  0  0  0 11  1  0  0  0 10  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  1  0  0  0  0  0  0  0 13]
 [11  0  2  0  0  0  0  0  0  0  8  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  1 11  0  0  0  0  0]
 [ 5  0 17  0  0  4 18  0 24 21  0 20  0  0 15  3]
 [ 0  0  0  0  0  0  0  0  0  0 14  2  0  0  0 14]
 [ 9  0  0  1  0  0  0  0  0  0  0  0  0  0  0 13]
 [ 0  0  0  0  0 14  0  0  0  0  0  0  0  0  0  7]
 [ 0  0  0  0  0  0  0  0  0  0  9  0  0  0  0 10]
 [ 1  1  0 15  0  5  0 20  0  0  6 14 23 26 19  0]]
